GO_REQUIRED_PREFIX=go1.26
GO_PROXY_REQUIRED=https://goproxy.cn,direct
DOCKER_REQUIRED_PREFIX="Docker version 29."
KUBECTL_REQUIRED_PREFIX=v1.36
KIND_REQUIRED_PREFIX=kind
HELM_REQUIRED_PREFIX=v4.
KIND_NODE_IMAGE=registry.cn-guangzhou.aliyuncs.com/yleoer/node:v1.35.0@sha256:452d707d4862f52530247495d180205e029056831160e22870e37e3f6c1ac31f